#!/usr/bin/python
import argparse
from commands import *

parser = argparse.ArgumentParser(
    description = 'Harvest time-tracking from the command line!'
)
subparsers = parser.add_subparsers()

login_parser = subparsers.add_parser(
    'login',
    help = 'Login to the command line utility.',
)
login_parser.add_argument('username', help = 'Your email address.')
login_parser.add_argument('password', help = 'Your password.')
login_parser.add_argument('subdomain', help = 'The subdomain of harvestapp.com where you log in.')
login_parser.set_defaults(func = login)

args = parser.parse_args()
args.func(args)
